---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	classify_ticket(classify_ticket)
	billing_node(billing_node)
	bug_node(bug_node)
	question_node(question_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> classify_ticket;
	classify_ticket -.-> billing_node;
	classify_ticket -.-> bug_node;
	classify_ticket -.-> question_node;
	billing_node --> __end__;
	bug_node --> __end__;
	question_node --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
